# ===========================================================================
#  Library Management System - build file
#
#  Targets
#     make            build the application (build/library_app)
#     make tests      build the test binaries (build/library_tests)
#     make driver     build the kernel module (delegates to driver/Makefile)
#     make all        application + tests + driver
#     make run        run the application
#     make test       build and run the whole test suite
#     make clean      remove build artefacts
#     make distclean  clean + remove generated data/log files
#
#  Build flags
#     C++17, warnings visible (-Wall -Wextra -pedantic), pthreads enabled.
#     Warnings are never suppressed.
# ===========================================================================

CXX      ?= g++
CXXFLAGS ?= -std=c++17 -Wall -Wextra -pedantic -Wshadow -pthread
CPPFLAGS += -Iinclude
LDFLAGS  += -pthread

# -MMD -MP makes the compiler emit a .d file listing the headers each object
# depends on, so editing a header rebuilds exactly the objects that need it.
DEPFLAGS := -MMD -MP

BUILD_DIR := build
OBJ_DIR   := $(BUILD_DIR)/obj

APP_SRCS := \
	src/Book.cpp \
	src/Member.cpp \
	src/Transaction.cpp \
	src/Authentication.cpp \
	src/FileManager.cpp \
	src/Logger.cpp \
	src/ReportManager.cpp \
	src/DriverClient.cpp \
	src/Library.cpp \
	src/main.cpp \
	src/system/ipc.cpp \
	src/system/thread_manager.cpp \
	src/system/process_manager.cpp \
	src/system/signal_handler.cpp

# main.cpp is linked only into the application, never into the tests.
LIB_SRCS := $(filter-out src/main.cpp,$(APP_SRCS))

TEST_SRCS := \
	tests/test_main.cpp \
	tests/unit_tests.cpp \
	tests/system_tests.cpp

APP_OBJS  := $(patsubst %.cpp,$(OBJ_DIR)/%.o,$(APP_SRCS))
LIB_OBJS  := $(patsubst %.cpp,$(OBJ_DIR)/%.o,$(LIB_SRCS))
TEST_OBJS := $(patsubst %.cpp,$(OBJ_DIR)/%.o,$(TEST_SRCS))
DEPS      := $(APP_OBJS:.o=.d) $(LIB_OBJS:.o=.d) $(TEST_OBJS:.o=.d)

APP      := $(BUILD_DIR)/library_app
TEST_BIN := $(BUILD_DIR)/library_tests

.PHONY: all app tests driver run test clean distclean help install-driver remove-driver

all: app tests

app: $(APP)

tests: $(TEST_BIN)

# --------------------------------------------------------------------------
# Compilation
# --------------------------------------------------------------------------
$(OBJ_DIR)/%.o: %.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) $(DEPFLAGS) -c $< -o $@

# Header dependencies generated by -MMD.
-include $(DEPS)

# --------------------------------------------------------------------------
# Linking
# --------------------------------------------------------------------------
$(APP): $(APP_OBJS)
	@mkdir -p $(dir $@)
	$(CXX) $(APP_OBJS) -o $@ $(LDFLAGS)

$(TEST_BIN): $(TEST_OBJS) $(LIB_OBJS)
	@mkdir -p $(dir $@)
	$(CXX) $(TEST_OBJS) $(LIB_OBJS) -o $@ $(LDFLAGS)

# --------------------------------------------------------------------------
# Convenience
# --------------------------------------------------------------------------
driver:
	$(MAKE) -C driver

install-driver: driver
	sudo insmod driver/library_driver.ko
	@ls -l /dev/library_driver

remove-driver:
	sudo rmmod library_driver

run: app
	@mkdir -p data logs
	./$(APP)

test: tests
	@mkdir -p data logs
	./$(TEST_BIN)
	@bash tests/run_cli_tests.sh

clean:
	rm -rf $(BUILD_DIR)
	$(MAKE) -C driver clean

distclean: clean
	rm -rf logs/library.log data/books.dat data/members.dat \
	       data/transactions.dat data/admin.dat

help:
	@sed -n '1,25p' Makefile